export const PREDEFINED_HEADERS = [
  { id: 'none', label: 'بدون سربرگ (حذف)' },
  {
    id: 'header-std-1',
    label: 'قالب استاندارد ۱',
    layout: 'standard-1',
    standard1: {
      bismillah: 'بسمه تعالی',
      studentName: 'نام و نام خانوادگی:',
      centerText: 'اداره آموزش و پرورش\nآزمون هماهنگ',
      examDate: 'تاریخ:',
      stampText: 'محل مهر',
      schoolName: 'آموزشگاه:',
      examStartTime: 'ساعت شروع:',
      pageCount: 'تعداد صفحه:',
      examDuration: 'مدت آزمون:',
      pageNumber: 'صفحه:',
      questionCount: 'تعداد سوال:',
      scoreNumeric: 'نمره عدد:',
      examSubject: 'درس:',
      scoreWritten: 'نمره حروف:',
    },
  },
  {
    id: 'header-std-4',
    label: 'قالب مینیمال',
    layout: 'standard-4',
    standard4: {
      rightLabel1: 'نام و نام خانوادگی:',
      centerLine1: 'بسمه تعالی',
      centerLine2: 'آزمون پایان ترم',
      centerLine3: '',
      leftLabel1: 'تاریخ:',
      rightLabel2: 'پایه و کلاس:',
      leftLabel2: 'زمان:',
      rightLabel3: 'شماره داوطلب:',
      leftLabel3: 'نمره:',
      rightLabel4: 'نام درس:',
      questionCountLabel: 'تعداد سوال:',
      pageCountLabel: 'تعداد صفحه:',
      bottomSignLabel: 'امضای مصحح:',
      bottomScoreNumeric: 'نمره به عدد:',
      bottomScoreWritten: 'نمره به حروف:',
    },
  },
];